### ISSUE TITLE
BUG:  neptune.utils.stringify_unsupported does not support 64-bit integers

### ISSUE THREAD

**Issue by pizzawithsucuk** [neptune-ai/neptune-client#1285]
### Describe the bug
Calling neptune.utils.stringify_unsupported() on integers larger than 2147483647 leads to neptune.common.exceptions.ClientHttpError when logging the value. 

### Reproduction

from neptune.utils import stringify_unsupported
import neptune 

run = neptune.init_run(project='some_project_id')
run['x'] = stringify_unsupported(2147483648)

### Expected behavior
As I understand, neptune does not support some data types like tuples and 64-bit integers. Calling stringify_unsupported allows unsupported data types to be logged as strings. This is not the case for 64-bit integers. I expected that 64-bit integers could be logged as strings with stingify_unsupported. Though, I don't know what behavior is desired by the team.

### Traceback
Exception in thread NeptuneAsyncOpProcessor:
Traceback (most recent call last):
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/neptune/common/backends/utils.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/neptune/internal/backends/hosted_neptune_backend.py", line 642, in _execute_operations
    result = self.leaderboard_client.api.executeOperations(**kwargs).response().result
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/neptune/internal/backends/swagger_client_wrapper.py", line 99, in __call__
    self.handle_neptune_http_errors(e.response, exception=e)
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/neptune/internal/backends/swagger_client_wrapper.py", line 92, in handle_neptune_http_errors
    raise exception
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/neptune/internal/backends/swagger_client_wrapper.py", line 97, in __call__
    return FinishedApiResponseFuture(future.response())  # wait synchronously
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/bravado/http_future.py", line 200, in response
    swagger_result = self._get_swagger_result(incoming_response)
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/bravado/http_future.py", line 124, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/bravado/http_future.py", line 300, in _get_swagger_result
    unmarshal_response(
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/bravado/http_future.py", line 353, in unmarshal_response
    raise_on_expected(incoming_response)
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/bravado/http_future.py", line 420, in raise_on_expected
    raise make_http_exception(
bravado.exception.HTTPBadRequest: 400 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/neptune/internal/operation_processors/async_operation_processor.py", line 226, in run
    super().run()
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/neptune/internal/threading/daemon.py", line 53, in run
    self.work()
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/neptune/internal/operation_processors/async_operation_processor.py", line 242, in work
    self.process_batch([element.obj for element in batch], batch[-1].ver)
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/neptune/internal/threading/daemon.py", line 76, in wrapper
    result = func(self_, *args, **kwargs)
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/neptune/internal/operation_processors/async_operation_processor.py", line 255, in process_batch
    processed_count, errors = self._processor._backend.execute_operations(
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/neptune/internal/backends/hosted_neptune_backend.py", line 484, in execute_operations
    self._execute_operations(
  File "/Users/rathjjgf/venvs/py39/lib/python3.9/site-packages/neptune/common/backends/utils.py", line 95, in wrapper
    raise ClientHttpError(e.status_code, e.response.text) from e
neptune.common.exceptions.ClientHttpError: 

----ClientHttpError-----------------------------------------------------------------------

The Neptune server returned the status 400.

The server response was:
{"errorType":"MALFORMED_JSON_REQUEST","code":400,"title":"400: Malformed JSON request"}

Verify the correctness of your call or contact Neptune support.

Need help?-> https://docs.neptune.ai/getting_help

### Environment
**The output of `pip list`:**
```
anyio                    3.6.2
appnope                  0.1.3
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
attrs                    22.2.0
backcall                 0.2.0
beautifulsoup4           4.11.1
bleach                   5.0.1
boto3                    1.26.52
botocore                 1.29.52
bravado                  11.0.3
bravado-core             5.17.1
certifi                  2022.12.7
cffi                     1.15.1
charset-normalizer       3.0.1
click                    8.1.3
comm                     0.1.2
contourpy                1.0.7
cycler                   0.11.0
debugpy                  1.6.5
decorator                5.1.1
defusedxml               0.7.1
entrypoints              0.4
executing                1.2.0
fastjsonschema           2.16.2
fonttools                4.38.0
fqdn                     1.5.1
future                   0.18.3
gitdb                    4.0.10
GitPython                3.1.30
idna                     3.4
importlib-metadata       6.0.0
ipykernel                6.20.2
ipython                  8.8.0
ipython-genutils         0.2.0
ipywidgets               8.0.4
isoduration              20.11.0
jedi                     0.18.2
Jinja2                   3.1.2
jmespath                 1.0.1
jsonpointer              2.3
jsonref                  1.1.0
jsonschema               4.17.3
jupyter                  1.0.0
jupyter_client           7.4.9
jupyter-console          6.4.4
jupyter_core             5.1.3
jupyter-events           0.6.3
jupyter_server           2.1.0
jupyter_server_terminals 0.4.4
jupyterlab-pygments      0.2.2
jupyterlab-widgets       3.0.5
kiwisolver               1.4.4
MarkupSafe               2.1.2
matplotlib               3.6.3
matplotlib-inline        0.1.6
mistune                  2.0.4
monotonic                1.6
msgpack                  1.0.4
nbclassic                0.4.8
nbclient                 0.7.2
nbconvert                7.2.8
nbformat                 5.7.3
neptune                  1.0.2
nest-asyncio             1.5.6
notebook                 6.5.2
notebook_shim            0.2.2
numpy                    1.24.1
oauthlib                 3.2.2
packaging                23.0
pandas                   1.5.3
pandocfilters            1.5.0
parso                    0.8.3
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.4.0
pip                      23.0.1
platformdirs             2.6.2
plotly                   5.12.0
prometheus-client        0.15.0
prompt-toolkit           3.0.36
psutil                   5.9.4
ptyprocess               0.7.0
pure-eval                0.2.2
pycparser                2.21
Pygments                 2.14.0
PyJWT                    2.6.0
pyparsing                3.0.9
pyrsistent               0.19.3
python-dateutil          2.8.2
python-json-logger       2.0.4
pytz                     2022.7.1
PyYAML                   6.0
pyzmq                    25.0.0
qtconsole                5.4.0
QtPy                     2.3.0
requests                 2.28.2
requests-oauthlib        1.3.1
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
rfc3987                  1.3.8
s3transfer               0.6.0
scipy                    1.10.0
Send2Trash               1.8.0
setuptools               65.5.1
simplejson               3.18.1
six                      1.16.0
smmap                    5.0.0
sniffio                  1.3.0
soupsieve                2.3.2.post1
stack-data               0.6.2
swagger-spec-validator   3.0.3
tenacity                 8.1.0
terminado                0.17.1
tinycss2                 1.2.1
torch                    1.13.1
torchvision              0.14.1
tornado                  6.2
traitlets                5.8.1
typing_extensions        4.4.0
uri-template             1.2.0
urllib3                  1.26.14
wcwidth                  0.2.6
webcolors                1.12
webencodings             0.5.1
websocket-client         1.4.2
wheel                    0.38.4
widgetsnbextension       4.0.5
zipp                     3.11.0
```
**The operating system you're using:**
macOS 13.2.1 (22D68)
**The output of `python --version`:**
Python 3.9.6

**Comment by Blaizzy** [comment]
Hi @pizzawithsucuk 

Prince here, 

Thanks for reaching out!

Let me check with the devs and I will get back to you as soon as possible.

**Comment by Blaizzy** [comment]
Hey @pizzawithsucuk ,

I just heard from the devs,

`stringify_unsupported` was created only to handle the backward incompatibility between 1.0.0 and <1.0.0. As you pointed out it supports only standard signed integers up to 2^32. 

The suggestion I have for your case is to use explicit `str(some_big_number)` instead of `stringify_unsupported`.

**Comment by Blaizzy** [comment]
Let me know if this helps you!

**Comment by pizzawithsucuk** [comment]
Hello @Blaizzy,

If this is the desired behavior, it is not a bug. Thanks for the clarification.

**Comment by Blaizzy** [comment]
Most welcome! 

If anything else pops up, do let me know, and I'll be happy to help. 

Have a good day! ☀️
