### ISSUE TITLE
BUG: cannot log metrics from different processes/threads to same run

### ISSUE THREAD

**Issue by aljeshishe** [neptune-ai/neptune-client#1579]
### Describe the bug
My training procedure is parallelized using processes/threads
I want to log data to Neptune.

This case does not work because of different reasons:
1. Sometimes I observe multiple following errors:
```
Error occurred during asynchronous operation processing: Timestamp must be non-decreasing for series attribute: metric/a. Invalid point: 2023-11-30T17:54:05.241Z
```
3. Usually netpune run contains less than the expected number of points(1000)
4. Sometimes I see different errors like following:
```
Unexpected error occurred in Neptune background thread: Killing Neptune asynchronous thread. All data is safe on disk and can be later synced manually using `neptune sync` command.
Exception in thread NeptuneAsyncOpProcessor:
Traceback (most recent call last):
  File "/home/ubuntu/.asdf/installs/python/3.10.12/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/internal/operation_processors/async_operation_processor.py", line 227, in run
    super().run()
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/internal/threading/daemon.py", line 95, in run
    self.work()
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/internal/operation_processors/async_operation_processor.py", line 243, in work
    self.process_batch([element.obj for element in batch], batch[-1].ver)
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/internal/threading/daemon.py", line 120, in wrapper
    result = func(self_, *args, **kwargs)
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/internal/operation_processors/async_operation_processor.py", line 256, in process_batch
    processed_count, errors = self._processor._backend.execute_operations(
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/internal/backends/hosted_neptune_backend.py", line 467, in execute_operations
    self._execute_upload_operations_with_400_retry(
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/internal/backends/hosted_neptune_backend.py", line 571, in _execute_upload_operations_with_400_retry
    return self._execute_upload_operations(
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/internal/backends/hosted_neptune_backend.py", line 547, in _execute_upload_operations
    upload_errors = upload_file_set_attribute(
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/internal/backends/hosted_file_operations.py", line 174, in upload_file_set_attribute
    _multichunk_upload_with_retry(
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/internal/backends/hosted_file_operations.py", line 286, in _multichunk_upload_with_retry
    return _multichunk_upload(upload_entry, swagger_client, query_params, multipart_config, urlset)
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/internal/backends/hosted_file_operations.py", line 307, in _multichunk_upload
    result = upload_raw_data(
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/common/backends/utils.py", line 70, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/internal/backends/hosted_file_operations.py", line 377, in upload_raw_data
    ApiMethodWrapper.handle_neptune_http_errors(response)
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/internal/backends/swagger_client_wrapper.py", line 88, in handle_neptune_http_errors
    handle_json_errors(
  File "/home/ubuntu/mlrobot2/.venv/lib/python3.10/site-packages/neptune/api/exceptions_utils.py", line 39, in handle_json_errors
    raise source_exception
TypeError: exceptions must derive from BaseException
```

### Reproduction
```
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
import time
import uuid
import neptune

custom_run_id = str(uuid.uuid4())

def train():
    run = neptune.init_run(
        project="AnalyzerAB/MLMetrics",
        api_token="...",
        custom_run_id=custom_run_id,
    )
    for i in range(100):
        time.sleep(0.1)
        run[f"metric/a"].append(i)
    run.stop()
        


workers = 10
with ThreadPoolExecutor(max_workers=workers) as executor:
    futures = [executor.submit(train) for i in range(workers)]
    for future in futures:
        future.result()
        
        
```
### Expected behavior
I expect 100*10= 1000 points in Neptune run and no errors.

### Traceback
If applicable, add traceback or log output/screenshots to help explain your problem.
### Environment
**The output of `pip list`:**
```
Package                  Version     Editable project location
------------------------ ----------- -------------------------
antlr4-python3-runtime   4.9.3
anyio                    3.7.1
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
arrow                    1.2.3
asttokens                2.2.1
attrs                    23.1.0
autoflake                2.2.1
autopep8                 2.0.4
backcall                 0.2.0
backoff                  2.2.1
beautifulsoup4           4.12.2
black                    23.9.1
bleach                   6.0.0
blessings                1.7
boto3                    1.26.134
botocore                 1.29.162
bravado                  11.0.3
bravado-core             5.17.1
cachetools               5.3.1
certifi                  2023.5.7
cffi                     1.15.1
chardet                  5.1.0
charset-normalizer       3.1.0
clearml                  1.11.1
click                    8.1.3
cloudpickle              2.2.1
codecov                  2.1.13
colorama                 0.4.6
coloredlogs              15.0.1
colour-runner            0.1.1
comm                     0.1.3
contourpy                1.1.0
coverage                 7.2.7
cycler                   0.11.0
dask                     2023.6.1
datacompy                0.10.1
debugpy                  1.6.7
decorator                5.1.1
deepdiff                 6.3.0
defusedxml               0.7.1
distlib                  0.3.6
docutils                 0.20.1
exceptiongroup           1.1.1
execnet                  1.9.0
executing                1.2.0
fastjsonschema           2.17.1
filelock                 3.12.2
fonttools                4.40.0
fqdn                     1.5.1
fsspec                   2023.6.0
furl                     2.1.3
future                   0.18.3
gitdb                    4.0.10
GitPython                3.1.31
humanfriendly            10.0
hydra-core               1.3.2
idna                     3.4
importlib-metadata       6.7.0
iniconfig                2.0.0
ipykernel                6.24.0
ipython                  8.14.0
ipython-genutils         0.2.0
ipywidgets               8.0.7
isoduration              20.11.0
isort                    5.12.0
jedi                     0.18.2
Jinja2                   3.1.2
jmespath                 1.0.1
joblib                   1.2.0
jsonpointer              2.4
jsonref                  1.1.0
jsonschema               4.17.3
jupyter                  1.0.0
jupyter_client           8.3.0
jupyter-console          6.6.3
jupyter_core             5.3.1
jupyter-events           0.6.3
jupyter_server           2.7.0
jupyter_server_terminals 0.4.4
jupyterlab-pygments      0.2.2
jupyterlab-widgets       3.0.8
kiwisolver               1.4.4
lightgbm                 3.3.5
llvmlite                 0.40.1
locket                   1.0.0
lockfile                 0.12.2
luigi                    3.3.0
MarkupSafe               2.1.3
matplotlib               3.7.1
matplotlib-inline        0.1.6
mistune                  3.0.1
mlrobot                  0.1.0       /home/ubuntu/mlrobot2
monotonic                1.6
msgpack                  1.0.5
mypy-extensions          1.0.0
nbclassic                1.0.0
nbclient                 0.8.0
nbconvert                7.7.1
nbformat                 5.9.1
neptune                  1.3.2
nest-asyncio             1.5.6
notebook                 6.5.4
notebook_shim            0.2.3
numba                    0.57.1
numpy                    1.24.2
oauthlib                 3.2.2
omegaconf                2.3.0
ordered-set              4.1.0
orderedmultidict         1.0.1
overrides                7.3.1
packaging                23.1
pandas                   1.5.3
pandocfilters            1.5.0
parse                    1.19.1
parso                    0.8.3
partd                    1.4.0
pathlib2                 2.3.7.post1
pathspec                 0.11.1
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.5.0
pip                      23.2.1
platformdirs             3.8.0
pluggy                   1.2.0
prometheus-client        0.17.1
prompt-toolkit           3.0.39
psutil                   5.9.5
ptyprocess               0.7.0
pure-eval                0.2.2
pyarrow                  11.0.0
pycodestyle              2.11.0
pycparser                2.21
pyflakes                 3.1.0
Pygments                 2.15.1
PyJWT                    2.4.0
pyparsing                3.1.0
pyproject-api            1.5.2
pyrsistent               0.19.3
pytest                   7.4.0
pytest-env               0.8.2
pytest-ordering          0.6
pytest-rerunfailures     11.1.2
pytest-xdist             3.3.1
python-daemon            3.0.1
python-dateutil          2.8.2
python-dotenv            1.0.0
python-json-logger       2.0.7
pytz                     2023.3
PyYAML                   6.0
pyzmq                    25.1.0
qtconsole                5.4.3
QtPy                     2.3.1
requests                 2.31.0
requests-oauthlib        1.3.1
rfc3339-validator        0.1.4
rfc3986-validator        0.1.1
rfc3987                  1.3.8
rootpath                 0.1.1
s3transfer               0.6.1
scikit-learn             1.2.2
scipy                    1.9.3
Send2Trash               1.8.2
setuptools               68.0.0
shap                     0.41.0
simplejson               3.19.1
six                      1.16.0
slicer                   0.0.7
smmap                    5.0.0
sniffio                  1.3.0
soupsieve                2.4.1
stack-data               0.6.2
sultan                   0.9.1
swagger-spec-validator   3.0.3
tenacity                 8.2.2
termcolor                2.3.0
terminado                0.17.1
threadpoolctl            3.1.0
tinycss2                 1.2.1
tomli                    2.0.1
toolz                    0.12.0
tornado                  6.3.2
tox                      4.6.3
tqdm                     4.65.0
traitlets                5.9.0
typing_extensions        4.6.3
uri-template             1.3.0
urllib3                  1.26.16
virtualenv               20.23.1
wcwidth                  0.2.6
webcolors                1.13
webencodings             0.5.1
websocket-client         1.6.1
websockets               10.1
wheel                    0.40.0
widgetsnbextension       4.0.8
zipp                     3.15.0
```
**The operating system you're using:**
ubuntu 20.04
**The output of `python --version`:**
Python 3.10.12

**Comment by aljeshishe** [comment]
Hi @SiddhantSadangi 
Thank you for getting back to me. 
1. I've updated neptune version
2. It helped with multithreaded case (one neptune client instance per multiple training thread)
3. I still face issue with multiprocess case (one netpune client per training process). 

As I understood from the link you provided, a possible workaround would be to convert a multiprocess case into a single process case: 
- create multiprocess queue in the main process
- send data to this queue from training processes
- report data from this queue to Neptune. 
This is doable, but I wonder if Neptune offers an easier solution?

**Comment by SiddhantSadangi** [comment]
Hey @aljeshishe 

I am glad to know that the issues with multithreading were resolved. 🎉 

Generally, with all loggers, it is best to log metrics from the main process to prevent conflicts. 
However, if your use case prevents you from doing that, we recommend using `sync()` at regular intervals so that all the processes are synced with the servers. Here's a best practices guide that also elaborates why this is needed when using distributed setups: https://docs.neptune.ai/usage/best_practices/#distributed-computing

Please let me know if you still run into issues even after following the above recommendations.
