### ISSUE TITLE
Error: X-coordinates must be strictly increasing

### ISSUE THREAD

**Issue by elsieyin** [neptune-ai/neptune-client#278]
sorry to bother you guys, really great app
```python
# Connect your script to Neptune

PARAMS = {'boosting_type': 'gbdt',
          'objective': 'binary',
          'metric': 'auc',
          'bagging_fraction': 0.7,
          'seed': 2020,
          }

# Create an experiment and log hyperparameters
neptune.create_experiment(name='test-lgb-1',
                          description='1st test on LC data, train-test-split, basic-fe',
                          params={**PARAMS,
                                  # 'num_boosting_round': NUM_BOOSTING_ROUNDS
                                  },
                          upload_source_files=['train.py', 'environment.yaml'],
                          )

# read data
train = pd.read_csv('cfn-train.csv')
test = pd.read_csv('cfn-testa.csv')

fea = [f for f in train.columns if f not in ['id', 'isDefault']]
X_train = train[fea]
X_test = test[fea]
y_train = train['isDefault']

folds = 5
seed = 2008
kf = KFold(n_splits=folds, shuffle=True, random_state=seed)

# _______________________________

cv_scores = []
for i, (train_ind, valid_ind) in enumerate(kf.split(X_train, y_train)):
    print('************************************ {} ************************************'.format(str(i + 1)))
    X_train_split, y_train_split, X_val, y_val = X_train.iloc[train_ind], y_train[train_ind], X_train.iloc[valid_ind], y_train[valid_ind]

    train_matrix = lgb.Dataset(X_train_split, label=y_train_split)  # categorical_feature = ['grade, subGrade']
    valid_matrix = lgb.Dataset(X_val, label=y_val)

    gbm = lgb.train(PARAMS,
                    train_set=train_matrix,
                    # num_boost_round=NUM_BOOSTING_ROUNDS,
                    valid_sets=valid_matrix,
                    verbose_eval=200,
                    early_stopping_rounds=200,
                    # valid_names=['train', 'valid'],
                    callbacks=[neptune_monitor()],  # monitor learning curves (prefix)
                    )

    val_pred = gbm.predict(X_val, num_iteration=gbm.best_iteration)
    cv_scores.append(roc_auc_score(y_val, val_pred))
    print(cv_scores)
```

I am having this bug . I don't know how to fix... I searched and found an article, but really got me confused...

```python
Failed to send channel value.
Traceback (most recent call last):
  File "F:\Anaconda\envs\kaggle\lib\site-packages\neptune\internal\channels\channels_values_sender.py", line 156, in _send_values
    self._experiment._send_channels_values(channels_with_values)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\neptune\experiments.py", line 1138, in _send_channels_values
    self._backend.send_channels_values(self, channels_with_values)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\neptune\utils.py", line 210, in wrapper
    return func(*args, **kwargs)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\neptune\internal\backends\hosted_neptune_backend.py", line 560, in send_channels_values
    raise ChannelsValuesSendBatchError(experiment.id, batch_errors)
neptune.api_exceptions.ChannelsValuesSendBatchError: Received batch errors sending channels' values to experiment LEN-9. Cause: Error(code=400, message='X-coordinates must be strictly increasing for channel: 4176ea13-112e-41f7-a353-fcd8348b3379. Invalid point: InputChannelValue(timestamp=2020-09-30T07:11:18.643Z, x=0.0, numericValue=0.7006723423306764, textVa', type=None) (metricId: '4176ea13-112e-41f7-a353-fcd8348b3379', x: 0.0) Skipping 100 values.
```

**Comment by elsieyin** [comment]
BTW  how to do folds? I see an example on xgb, but looked and found no code

**Comment by PiotrJander** [comment]
Hi @elsieyin , I found this note in the docs of [our integration with LightGBM](https://docs.neptune.ai/api-reference/neptunecontrib/monitoring/lightgbm/index.html#:~:text=fold):

"If you are running a k-fold validation it is a good idea to add the k-fold prefix and pass it to the neptune_monitor function:

```python
prefix='fold_{}'.format(fold_id)
monitor = neptune_monitor(prefix)
```
"

I think (just a guess, haven't tested this) that you would have to change your code to look like this:

```python
for i, (train_ind, valid_ind) in enumerate(kf.split(X_train, y_train)):
    print('************************************ {} ************************************'.format(str(i + 1)))
    X_train_split, y_train_split, X_val, y_val = X_train.iloc[train_ind], y_train[train_ind], X_train.iloc[valid_ind], y_train[valid_ind]

    train_matrix = lgb.Dataset(X_train_split, label=y_train_split)  # categorical_feature = ['grade, subGrade']
    valid_matrix = lgb.Dataset(X_val, label=y_val)

    gbm = lgb.train(PARAMS,
                    train_set=train_matrix,
                    # num_boost_round=NUM_BOOSTING_ROUNDS,
                    valid_sets=valid_matrix,
                    verbose_eval=200,
                    early_stopping_rounds=200,
                    # valid_names=['train', 'valid'],
                    callbacks=[neptune_monitor('fold_{}'.format(i))],  # monitor learning curves (prefix)
                    )

    val_pred = gbm.predict(X_val, num_iteration=gbm.best_iteration)
    cv_scores.append(roc_auc_score(y_val, val_pred))
    print(cv_scores)
```

Could you see if this works and let us know?

**Comment by elsieyin** [comment]
@PiotrJander thank you very much for helping. I noticed that code, but with your demenstration i finally seem to get sense.
I tried this morning,but
```python
for i, (train_ind, valid_ind) in enumerate(kf.split(X_train, y_train)):
    print('************************************ {} ************************************'.format(str(i + 1)))
    X_train_split, y_train_split, X_val, y_val = X_train.iloc[train_ind], y_train[train_ind], X_train.iloc[valid_ind], y_train[valid_ind]

    train_matrix = lgb.Dataset(X_train_split, label=y_train_split)  # categorical_feature = ['grade, subGrade']
    valid_matrix = lgb.Dataset(X_val, label=y_val)

    gbm = lgb.train(PARAMS,
                    train_set=train_matrix,
                    # num_boost_round=NUM_BOOSTING_ROUNDS,
                    valid_sets=valid_matrix,
                    verbose_eval=200,
                    early_stopping_rounds=200,
                    # valid_names=['train', 'valid'],
                    callbacks=[neptune_monitor('fold_{}'.format(i))],  # monitor learning curves (prefix)
                    )

    val_pred = gbm.predict(X_val, num_iteration=gbm.best_iteration)
    cv_scores.append(roc_auc_score(y_val, val_pred))
    print(cv_scores)
```
but I don't know
```python
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.18.1
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] on win32
In[2]: runfile('F:/iPynb/LendingClub/train.py', wdir='F:/iPynb/LendingClub')
https://ui.neptune.ai/ria230/LendingClub/e/LEN-11
************************************ 1 ************************************
[LightGBM] [Warning] Starting from the 2.1.2 version, default value for the "boost_from_average" parameter in "binary" objective is true.
This may cause significantly different results comparing to the previous versions of LightGBM.
Try to set boost_from_average=false, if your old models produce bad results
[LightGBM] [Info] Number of positive: 127757, number of negative: 512243
[LightGBM] [Info] Total Bins 3742
[LightGBM] [Info] Number of data: 640000, number of used features: 44
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.199620 -> initscore=-1.388669
[LightGBM] [Info] Start training from score -1.388669
Traceback (most recent call last):
  File "F:\Anaconda\envs\kaggle\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-8cbdee32f5a9>", line 1, in <module>
    runfile('F:/iPynb/LendingClub/train.py', wdir='F:/iPynb/LendingClub')
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "F:\IDE\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/iPynb/LendingClub/train.py", line 69, in <module>
    callbacks=[neptune_monitor('fold_{}'.format(i))],  # monitor learning curves (prefix)
  File "F:\Anaconda\envs\kaggle\lib\site-packages\lightgbm\engine.py", line 264, in train
    evaluation_result_list=evaluation_result_list))
  File "F:\Anaconda\envs\kaggle\lib\site-packages\neptunecontrib\monitoring\lightgbm.py", line 85, in callback
    _exp.send_metric(channel_name, x=env.iteration, y=loss_value)
AttributeError: 'str' object has no attribute 'send_metric'
```

**Comment by elsieyin** [comment]
```python
cv_scores = []

for i, (train_ind, valid_ind) in enumerate(kf.split(X_train, y_train)):
    print('************************************ {} ************************************'.format(str(i + 1)))
    X_train_split, y_train_split, X_val, y_val = X_train.iloc[train_ind], y_train[train_ind], X_train.iloc[valid_ind], y_train[valid_ind]

    train_matrix = lgb.Dataset(X_train_split, label=y_train_split)  # categorical_feature = ['grade, subGrade']
    valid_matrix = lgb.Dataset(X_val, label=y_val)

    prefix = 'fold{}_'.format(i)

    gbm = lgb.train(PARAMS,
                    train_set=train_matrix,
                    # num_boost_round=NUM_BOOSTING_ROUNDS,
                    valid_sets=valid_matrix,
                    verbose_eval=200,
                    early_stopping_rounds=200,
                    valid_names=['train', 'valid'],
                    callbacks=[neptune_monitor(exp, prefix)],  # monitor learning curves (prefix)
                    )

    val_pred = gbm.predict(X_val, num_iteration=gbm.best_iteration)
    cv_scores.append(roc_auc_score(y_val, val_pred))
    print(cv_scores)
```
I read a little source code, and seem to fix this problem, you have to pass the experiment, and prefix, prefix is a string, it has no attribute 'send_metric', while, experiment has.

**Comment by elsieyin** [comment]
alas it's a bit difficult for me , I still don't know how to add valid auc log... why few people use this, it's such a great app!

**Comment by PiotrJander** [comment]
Hi @elsieyin , good to see that you got `neptune_monitor` working - you're right, you have to do `neptune_monitor(exp, prefix)` or `neptune_monitor(prefix=prefix)` - we'll need to fix our documentation.

As for your problem with adding a valid  auc log, I don't know the logic of your model, but you should be able to log any number with 

`neptune.log_metric('metric_name', number)`

If you have a list of number you need to log, you can log them in a loop:

```
for n in number_list:
    neptune.log_metric('metric_name', n)
```

I hope this solves your problem.

By the way, we try to keep Github issues as a place specifically for tracking bugs in the Neptune client. If you have more general questions about using Neptune, you're more than welcome to talk to us through Intercom on Neptune website (click a chat icon in the bottom right corner).

**Comment by elsieyin** [comment]
Ok and I'm sorry，thnx)

**Comment by elsieyin** [comment]
I do find a bug here, However, it seems you guys haven't wrote code to log lightgbm callbacks like xgboost do. 
still don't know how to log train's overall mean auc...
and on the experiment chart on neptune.ai, whenever I created a `neptune.log_metric()` , even if I deleted it or renamed it on my `train.py`, 
it's still on the sites' numeric logs, it doesn't collect itself when disposed

**Comment by Herudaio** [comment]
Hi @elsieyin! 

1) It's possible to "reset" a metric i.e. remove all values, but the metric itself (empty after reset) will remain. As of now, it's not possible to fully remove it.
2) As long as at least one experiment in the project has a metric with a given name it will appear in the experiments table.

Sorry for the late answer, hope that your problem was solved, and this clarification will still provide some value to you :)
