### ISSUE TITLE
ModuleNotFoundError: No module named 'oauthlib.oauth2' but it is installed

### ISSUE THREAD

**Issue by BlackArbsCEO** [neptune-ai/neptune-client#368]
I'm trying to run an experiment but I am getting an error:

```
neptune.init("blackarbsceo/hpo-es-features", api_token=api_key)
neptune.create_experiment(
    "hyperparameter-optuna-rf-test", upload_source_files=["*.py"]
)
neptune_callback = optuna_utils.NeptuneCallback(log_study=True, log_charts=True)
Traceback (most recent call last):
  File "C:\Users\kngka\Anaconda3\envs\mlfinlab2\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-63e8b42c81c5>", line 17, in <module>
    import neptune
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\kngka\Anaconda3\envs\mlfinlab2\lib\site-packages\neptune\__init__.py", line 24, in <module>
    from neptune.internal.backends.hosted_neptune_backend import HostedNeptuneBackend
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\kngka\Anaconda3\envs\mlfinlab2\lib\site-packages\neptune\internal\backends\hosted_neptune_backend.py", line 58, in <module>
    from neptune.oauth import NeptuneAuthenticator
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\kngka\Anaconda3\envs\mlfinlab2\lib\site-packages\neptune\oauth.py", line 21, in <module>
    from oauthlib.oauth2 import TokenExpiredError, OAuth2Error
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.1.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'oauthlib.oauth2'
```

```
oauthlib                  3.1.0                    pypi_0    pypi
neptune-client            0.4.132+2.g26cdb5a          pypi_0    pypi
neptune-contrib           0.25.0                   pypi_0    pypi

**Comment by szymon-kuklewicz** [comment]
Hi

I cannot reproduce situation. Created fresh few environments with latest neptune-client 0.4.132 and same oauthlib 3.1.0 and could not make such error to occur. 

python -m pip install oauthlib==3.1.0
python -m pip install neptune-client==0.4.132

Can you please prepare reproduction steps starting from fresh environment?

Best regards,
Szymon

**Comment by aniezurawski** [comment]
Version `0.4.132+2.g26cdb5a` does not match any official release of `neptune-client`. How have you installed it? Looks like it was built from one of the latest commit on `master` branch.

**Comment by BlackArbsCEO** [comment]
I reinstalled it using the `pip install neptune-client==0.4.132` command but I had the same oauth error. I'm creating a new conda environment and will try again fresh.

**Comment by BlackArbsCEO** [comment]
new error. let me know if you want me to create a new issue for it.

```
Traceback (most recent call last):
  File "D:/PERSONAL/CODE_PROJECTS/blackarbs_algo_strategy_dev-master/scripts/neptune_machine_learning_scripts/run_es_feature_hyperoptuna_randomforest_mlfinlab_daily.py", line 17, in <module>
    import neptune
  File "C:\Users\kngka\Anaconda3\envs\mlfinlab3\lib\site-packages\neptune\__init__.py", line 24, in <module>
    from neptune.internal.backends.hosted_neptune_backend import HostedNeptuneBackend
  File "C:\Users\kngka\Anaconda3\envs\mlfinlab3\lib\site-packages\neptune\internal\backends\hosted_neptune_backend.py", line 53, in <module>
    from neptune.experiments import Experiment
  File "C:\Users\kngka\Anaconda3\envs\mlfinlab3\lib\site-packages\neptune\experiments.py", line 34, in <module>
    from neptune.internal.utils.image import get_image_content
  File "C:\Users\kngka\Anaconda3\envs\mlfinlab3\lib\site-packages\neptune\internal\utils\image.py", line 21, in <module>
    from PIL import Image
  File "C:\Users\kngka\Anaconda3\envs\mlfinlab3\lib\site-packages\PIL\Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\kngka\Anaconda3\envs\mlfinlab3\lib\site-packages\PIL\__init__.py)

Process finished with exit code 1
```
fresh install with `python 3.7` and `pillow` is installed.
package list:
```
absl-py                   0.11.0                   pypi_0    pypi
alembic                   1.5.0                    pypi_0    pypi
analytics-python          1.2.9                    pypi_0    pypi
ansi2html                 1.6.0                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
attrdict                  2.0.1                    pypi_0    pypi
attrs                     20.3.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
bravado                   11.0.2                   pypi_0    pypi
bravado-core              5.17.0                   pypi_0    pypi
brotli                    1.0.9                    pypi_0    pypi
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cachetools                4.2.0                    pypi_0    pypi
certifi                   2020.12.5        py37h03978a9_1    conda-forge
chardet                   4.0.0                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
cliff                     3.6.0                    pypi_0    pypi
cmaes                     0.7.0                    pypi_0    pypi
cmd2                      1.4.0                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
colorlog                  4.7.2                    pypi_0    pypi
cvxpy                     1.1.1                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.21                  pypi_0    pypi
dash                      1.14.0                   pypi_0    pypi
dash-bootstrap-components 0.10.3                   pypi_0    pypi
dash-core-components      1.10.2                   pypi_0    pypi
dash-cytoscape            0.2.0                    pypi_0    pypi
dash-html-components      1.0.3                    pypi_0    pypi
dash-renderer             1.6.0                    pypi_0    pypi
dash-table                4.9.0                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
ecos                      2.0.7.post1              pypi_0    pypi
flask                     1.1.2                    pypi_0    pypi
flask-compress            1.8.0                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
gitdb                     4.0.5                    pypi_0    pypi
gitpython                 3.1.12                   pypi_0    pypi
google-auth               1.24.0                   pypi_0    pypi
google-auth-oauthlib      0.4.2                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.34.1                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      2.10                     pypi_0    pypi
importlib-metadata        3.4.0                    pypi_0    pypi
ipykernel                 5.4.3                    pypi_0    pypi
ipython                   7.19.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
itsdangerous              1.1.0                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
joblib                    1.0.0                    pypi_0    pypi
jsonpointer               2.0                      pypi_0    pypi
jsonref                   0.2                      pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter-client            6.1.11                   pypi_0    pypi
jupyter-core              4.7.0                    pypi_0    pypi
jupyter-dash              0.3.1                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
llvmlite                  0.32.1                   pypi_0    pypi
mako                      1.1.4                    pypi_0    pypi
markdown                  3.3.3                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.2.1                    pypi_0    pypi
mlfinlab                  0.15.2                   pypi_0    pypi
monotonic                 1.5                      pypi_0    pypi
msgpack                   1.0.2                    pypi_0    pypi
neptune-client            0.4.132                  pypi_0    pypi
neptune-contrib           0.25.0                   pypi_0    pypi
networkx                  2.4                      pypi_0    pypi
numba                     0.49.1                   pypi_0    pypi
numpy                     1.18.5                   pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
openssl                   1.1.1i               h8ffe710_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
optuna                    2.4.0                    pypi_0    pypi
osqp                      0.6.2.post0              pypi_0    pypi
packaging                 20.8                     pypi_0    pypi
pandas                    1.0.4                    pypi_0    pypi
parso                     0.8.1                    pypi_0    pypi
patsy                     0.5.1                    pypi_0    pypi
pbr                       5.5.1                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.1.0                    pypi_0    pypi
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
planarity                 0.4.1                    pypi_0    pypi
plotly                    4.14.3                   pypi_0    pypi
pot                       0.7.0                    pypi_0    pypi
prettytable               0.7.2                    pypi_0    pypi
prompt-toolkit            3.0.10                   pypi_0    pypi
protobuf                  3.14.0                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pygments                  2.7.4                    pypi_0    pypi
pyjwt                     2.0.1                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyperclip                 1.8.1                    pypi_0    pypi
pyreadline                2.1                      pypi_0    pypi
pyrsistent                0.17.3                   pypi_0    pypi
python                    3.7.0             hc182675_1006    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python-editor             1.0.4                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.5                   pypi_0    pypi
pywin32                   300                      pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     21.0.1                   pypi_0    pypi
qdldl                     0.1.5.post0              pypi_0    pypi
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
retrying                  1.3.3                    pypi_0    pypi
rfc3987                   1.3.8                    pypi_0    pypi
rsa                       4.7                      pypi_0    pypi
scikit-learn              0.23.1                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
scs                       2.1.2                    pypi_0    pypi
setuptools                49.6.0           py37h03978a9_3    conda-forge
simplejson                3.17.2                   pypi_0    pypi
six                       1.15.0                   pypi_0    pypi
smmap                     3.0.4                    pypi_0    pypi
sqlalchemy                1.3.22                   pypi_0    pypi
sqlite                    3.34.0               h8ffe710_0    conda-forge
statsmodels               0.11.1                   pypi_0    pypi
stevedore                 3.3.0                    pypi_0    pypi
strict-rfc3339            0.7                      pypi_0    pypi
swagger-spec-validator    2.7.3                    pypi_0    pypi
tensorboard               2.2.2                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                2.2.1                    pypi_0    pypi
tensorflow-estimator      2.2.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.56.0                   pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
tzdata                    2020f                he74cb21_0    conda-forge
urllib3                   1.26.2                   pypi_0    pypi
vc                        14.2                 hb210afc_2    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_0    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
webcolors                 1.11.1                   pypi_0    pypi
websocket-client          0.57.0                   pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wincertstore              0.2             py37h03978a9_1006    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
zipp                      3.4.0                    pypi_0    pypi
```

**Comment by BlackArbsCEO** [comment]
looks like it may be an issue between pip, pillow and pycharm somehow.

**Comment by BlackArbsCEO** [comment]
closing now as the install has worked.
