### ISSUE TITLE
Not supported on linux-pcc64? 

### ISSUE THREAD

**Issue by piperod** [neptune-ai/neptune-client#430]
Hi, I am trying to get neptune to work in an IBM power 9  node. It seems that there is no conda or pip recipe for this architecture. I tried also installing from source, but I keep getting this error: neptune.exceptions.UnsupportedClientVersion: This client version (0+unknown) is not supported. Please install neptune-client>=0.4.0.

**Comment by aniezurawski** [comment]
Hi @piperod 

How exectly have you installed package from source?
Try to replace following line:
`__version__ = get_versions()['version']`
with this:
`__version__ = "0.5.1"`
in file `neptune/__init__.py`.

**Comment by piperod** [comment]
I did git checkout 0.4.5. But now I am getting this new error :

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/data/tserre/irodri15/Miscelaneous/neptune-client/neptune/__init__.py", line 22, in <module>
    from neptune.internal.backends.hosted_neptune_backend import HostedNeptuneBackend
  File "/gpfs/data/tserre/irodri15/Miscelaneous/neptune-client/neptune/internal/backends/hosted_neptune_backend.py", line 42, in <module>
    from neptune.experiments import Experiment
  File "/gpfs/data/tserre/irodri15/Miscelaneous/neptune-client/neptune/experiments.py", line 32, in <module>
    from neptune.internal.channels.channels_values_sender import ChannelsValuesSender
  File "/gpfs/data/tserre/irodri15/Miscelaneous/neptune-client/neptune/internal/channels/channels_values_sender.py", line 22, in <module>
    from future.moves import queue
  File "/media/data/anaconda3-ibm/envs/ibm_2021/lib/python3.6/site-packages/future/moves/__init__.py", line 8, in <module>
    import_top_level_modules()
  File "/media/data/anaconda3-ibm/envs/ibm_2021/lib/python3.6/site-packages/future/standard_library/__init__.py", line 810, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "/media/data/anaconda3-ibm/envs/ibm_2021/lib/python3.6/site-packages/future/standard_library/__init__.py", line 781, in __enter__
    module = __import__(m, level=0)
  File "/gpfs/data/tserre/irodri15/Fossils/Code/CycleGAN-Tensorflow-2/test.py", line 17, in <module>
    args = py.args_from_yaml(py.join(test_args.experiment_dir, 'settings.yml'))
  File "/media/data/anaconda3-ibm/envs/ibm_2021/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by piperod** [comment]
I installed by using 

pip install .

**Comment by aniezurawski** [comment]
0.4.5 is very old version. Checkout 0.5.1 or try what I suggested earlier.

**Comment by piperod** [comment]
I tried with 0.5.1 as well, but it seems it keeps complaining. I had to comment everything of neptune for now.

**Comment by aniezurawski** [comment]
> Hi @piperod
> 
> How exectly have you installed package from source?
> Try to replace following line:
> `__version__ = get_versions()['version']`
> with this:
> `__version__ = "0.9.4"`
> in file `neptune/__init__.py`.

Have you tried to change this line i code?

**Comment by pkasprzyk** [comment]
No contact from user for more than 3 months. Closing, @piperod feel free to reopen or create a new issue if you're still having any problems.
