### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by johanbook** [neptune-ai/neptune-client#497]
I tried using the neptune client using

```py
import neptune.new as neptune

run = neptune.init(project="myproject")
```
with the api token as a shell env. I have the following dependencies;
```
attrs==20.3.0
bravado==11.0.3
bravado-core==5.17.0
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
future==0.18.2
gitdb==4.0.7
GitPython==3.1.14
idna==2.10
jsonpointer==2.1
jsonref==0.2
jsonschema==3.2.0
monotonic==1.5
msgpack==1.0.2
neptune-client==0.9.3
numpy==1.20.2
oauthlib==3.1.0
packaging==20.9
pandas==1.2.3
Pillow==8.2.0
PyJWT==2.0.1
pyparsing==2.4.7
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2021.1
PyYAML==5.4.1
requests==2.25.1
requests-oauthlib==1.3.0
rfc3987==1.3.8
simplejson==3.17.2
six==1.15.0
smmap==4.0.0
strict-rfc3339==0.7
swagger-spec-validator==2.7.3
typing-extensions==3.7.4.3
urllib3==1.26.4
webcolors==1.11.1
websocket-client==0.58.0
```

but I get

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    run = neptune.init(project="myproject")
  File "/home/book/.local/share/virtualenvs/neptune-zhERauC2/lib/python3.8/site-packages/neptune/new/internal/init_impl.py", line 144, in init
    project_obj = backend.get_project(project)
  File "/home/book/.local/share/virtualenvs/neptune-zhERauC2/lib/python3.8/site-packages/neptune/new/internal/backends/utils.py", line 51, in wrapper
    return func(*args, **kwargs)
  File "/home/book/.local/share/virtualenvs/neptune-zhERauC2/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py", line 149, in get_project
    response = self.backend_client.api.getProject(projectIdentifier=project_id).response()
  File "/home/book/.local/share/virtualenvs/neptune-zhERauC2/lib/python3.8/site-packages/bravado/http_future.py", line 200, in response
    swagger_result = self._get_swagger_result(incoming_response)
  File "/home/book/.local/share/virtualenvs/neptune-zhERauC2/lib/python3.8/site-packages/bravado/http_future.py", line 124, in wrapper
    return func(self, *args, **kwargs)
  File "/home/book/.local/share/virtualenvs/neptune-zhERauC2/lib/python3.8/site-packages/bravado/http_future.py", line 300, in _get_swagger_result
    unmarshal_response(
  File "/home/book/.local/share/virtualenvs/neptune-zhERauC2/lib/python3.8/site-packages/bravado/http_future.py", line 335, in unmarshal_response
    incoming_response.swagger_result = unmarshal_response_inner(  # type: ignore
  File "/home/book/.local/share/virtualenvs/neptune-zhERauC2/lib/python3.8/site-packages/bravado/http_future.py", line 380, in unmarshal_response_inner
    content_value = response.json()
  File "/home/book/.local/share/virtualenvs/neptune-zhERauC2/lib/python3.8/site-packages/bravado/requests_client.py", line 160, in json
    return self._delegate.json(**kwargs)
  File "/home/book/.local/share/virtualenvs/neptune-zhERauC2/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/book/.local/share/virtualenvs/neptune-zhERauC2/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/book/.local/share/virtualenvs/neptune-zhERauC2/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/book/.local/share/virtualenvs/neptune-zhERauC2/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
```

Seems to be the same as #280 and #282 but with a more recent version of  `bravado`

**Comment by aniezurawski** [comment]
Hi @johanbook 

The issue does not seem to be related to #280 and #282.
We will investigate it as soon as possible. Have this error appeared once or is it repeatable?

**Comment by johanbook** [comment]
It is repeatable @aniezurawski. I have not been able to execute the python snippet I supplied without it occuring

**Comment by aniezurawski** [comment]
Your project name is invalid. Try `run = neptune.init(project="johanbook/myproject")`.

There should be a pretty error printed on stderr in case of such mistake. But it was not printed because of a bug. Thanks for catching it!
Also make sure that you are working with newly created projects (created after 31.03) when using new api (`neptune.new` module).

Let us know if it works.

**Comment by johanbook** [comment]
Yes, that fixes it. Thank you very much for the feedback.
