### ISSUE TITLE
Exceptions are not logged due to the 1000 character line limit

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-client#576]
This is probably not a minimal example but still quite a short one:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from time import time, sleep

import neptune.new as neptune
from neptune.new.types import File
import ray 

def function_with_quite_a_long_name_2(x):
    return function_with_quite_a_long_name(x)

def function_with_quite_a_long_name(x):
    if x > 0:
        return function_with_quite_a_long_name_2(x - 1)
    raise Exception("hi")

@ray.remote
def f(x, run_id):
    run = neptune.init('nnaisense/sandbox-new', run=run_id,
                       monitoring_namespace=f'monitoring/{x}',
                       source_files=[])
    print(function_with_quite_a_long_name(10))


def main():
    n_jobs = 1 
    run = neptune.init(
        'nnaisense/sandbox-new',
        name='name',
        description='',
        source_files=[],
        flush_period=10,
        mode='async',
        monitoring_namespace='monitoring/main'
    )   

    rid = run['sys/id'].fetch()
    run['params/main'] = {'asdf': 2}

    ray.init()
    ray.get([f.remote(i, rid) for i in range(n_jobs)])


if __name__ == '__main__':
    main()
```

This fails with an Exception but the exception is not fully logged so it is useless.
```bash
Warning: string series 'monitoring/main/traceback' value was longer than 1000 characters and was truncated. This warning is printed only once per series.
Traceback (most recent call last):
  File "err.py", line 45, in <module>
    main()
  File "err.py", line 41, in main
    ray.get([f.remote(i, rid) for i in range(n_jobs)])
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/ray/worker.py", line 1481, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::f() (pid=2001412, ip=192.168.1.66)
  File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task
  File "err.py", line 22, in f
    print(function_with_quite_a_long_name(10))
  File "err.py", line 14, in function_with_quite_a_long_name
    return function_with_quite_a_long_name_2(x - 1)
  File "err.py", line 10, in function_with_quite_a_long_name_2
    return function_with_quite_a_long_name(x)
  File "err.py", line 14, in function_with_quite_a_long_name
    return function_with_quite_a_long_name_2(x - 1)
  File "err.py", line 10, in function_with_quite_a_long_name_2
    return function_with_quite_a_long_name(x)
  File "err.py", line 14, in function_with_quite_a_long_name
    return function_with_quite_a_long_name_2(x - 1)
  File "err.py", line 10, in function_with_quite_a_long_name_2
    return function_with_quite_a_long_name(x)
  File "err.py", line 14, in function_with_quite_a_long_name
    return function_with_quite_a_long_name_2(x - 1)
  File "err.py", line 10, in function_with_quite_a_long_name_2
    return function_with_quite_a_long_name(x)
  File "err.py", line 14, in function_with_quite_a_long_name
    return function_with_quite_a_long_name_2(x - 1)
  File "err.py", line 10, in function_with_quite_a_long_name_2
    return function_with_quite_a_long_name(x)
  File "err.py", line 14, in function_with_quite_a_long_name
    return function_with_quite_a_long_name_2(x - 1)
  File "err.py", line 10, in function_with_quite_a_long_name_2
    return function_with_quite_a_long_name(x)
  File "err.py", line 14, in function_with_quite_a_long_name
    return function_with_quite_a_long_name_2(x - 1)
  File "err.py", line 10, in function_with_quite_a_long_name_2
    return function_with_quite_a_long_name(x)
  File "err.py", line 14, in function_with_quite_a_long_name
    return function_with_quite_a_long_name_2(x - 1)
  File "err.py", line 10, in function_with_quite_a_long_name_2
    return function_with_quite_a_long_name(x)
  File "err.py", line 14, in function_with_quite_a_long_name
    return function_with_quite_a_long_name_2(x - 1)
  File "err.py", line 10, in function_with_quite_a_long_name_2
    return function_with_quite_a_long_name(x)
  File "err.py", line 14, in function_with_quite_a_long_name
    return function_with_quite_a_long_name_2(x - 1)
  File "err.py", line 10, in function_with_quite_a_long_name_2
    return function_with_quite_a_long_name(x)
  File "err.py", line 15, in function_with_quite_a_long_name
    raise Exception("hi")
Exception: hiWarning: string series 'monitoring/main/stderr' value was longer than 1000 characters and was truncated. This warning is printed only once per series.

Shutting down background jobs, please wait a moment...
Done!
Waiting for the remaining 44 operations to synchronize with Neptune. Do not kill this process.
All 44 operations synced, thanks for waiting!

```

**Comment by Herudaio** [comment]
@wjaskowski just to double-check - do you see a full error message under `monitoring/stacktrace` path?

**Comment by wjaskowski** [comment]
I see the following in monitoring/stderr:
```

2021/05/24 16:50:00 | 2021-05-24 16:50:00,431 INFO services.py:1267 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
-- | --
2021/05/24 16:50:03 | &nbsp;
2021/05/24 16:50:03 | Warning: string series 'monitoring/main/traceback' value was longer than 1000 characters and was truncated. This warning is printed only once per series.
2021/05/24 16:50:03 | Traceback (most recent call last):
2021/05/24 16:50:03 | File "err.py", line 45, in &lt;module&gt;
2021/05/24 16:50:03 | &nbsp;
2021/05/24 16:50:03 | main()
2021/05/24 16:50:03 | &nbsp;
2021/05/24 16:50:03 | File "err.py", line 41, in main
2021/05/24 16:50:03 | &nbsp;
2021/05/24 16:50:03 | ray.get([f.remote(i, rid) for i in range(n_jobs)])
2021/05/24 16:50:03 | &nbsp;
2021/05/24 16:50:03 | File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
2021/05/24 16:50:03 | &nbsp;
2021/05/24 16:50:03 | return func(*args, **kwargs)
2021/05/24 16:50:03 | &nbsp;
2021/05/24 16:50:03 | File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/ray/worker.py", line 1481, in get
2021/05/24 16:50:03 | &nbsp;
2021/05/24 16:50:03 | raise value.as_instanceof_cause()
2021/05/24 16:50:03 | &nbsp;
2021/05/24 16:50:03 | ray.exceptions
2021/05/24 16:50:03 | .
2021/05/24 16:50:03 | RayTaskError
2021/05/24 16:50:03 | :
2021/05/24 16:50:03 | [36mray::f()[39m (pid=2001412, ip=192.168.1.66) File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task File "err.py", line 22, in f print(function_with_quite_a_long_name(10)) File "err.py", line 14, in function_with_quite_a_long_name return function_with_quite_a_long_name_2(x - 1) File "err.py", line 10, in function_with_quite_a_long_name_2 return function_with_quite_a_long_name(x) File "err.py", line 14, in function_with_quite_a_long_name return function_with_quite_a_long_name_2(x - 1) File "err.py", line 10, in function_with_quite_a_long_name_2 return function_with_quite_a_long_name(x) File "err.py", line 14, in function_with_quite_a_long_name return function_with_quite_a_long_name_2(x - 1) File "err.py", line 10, in function_with_quite_a_long_name_2 return function_with_quite_a_long_name(x) File "err.py", line 14, in function_with_quite_a_long_name return function_with_quite_a_long_name_2(x - 1) File "err.py", line
2021/05/24 16:50:03
```

And the following in monitoring/traceback:
```
2021/05/24 16:50:03	An uncaught exception occurred while run was active on worker roo.
2021/05/24 16:50:03	Making run as failed
2021/05/24 16:50:03	Traceback:
2021/05/24 16:50:03	File "err.py", line 45, in <module> main()
2021/05/24 16:50:03	File "err.py", line 41, in main ray.get([f.remote(i, rid) for i in range(n_jobs)])
2021/05/24 16:50:03	File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper return func(*args, **kwargs)
2021/05/24 16:50:03	File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/ray/worker.py", line 1481, in get raise value.as_instanceof_cause()
2021/05/24 16:50:03	RayTaskError('__main__.f', 'Traceback (most recent call last):\n File "python/ray/_raylet.pyx", line 505, in ray._raylet.execute_task\n File "err.py", line 22, in f\n print(function_with_quite_a_long_name(10))\n File "err.py", line 14, in function_with_quite_a_long_name\n return function_with_quite_a_long_name_2(x - 1)\n File "err.py", line 10, in function_with_quite_a_long_name_2\n return function_with_quite_a_long_name(x)\n File "err.py", line 14, in function_with_quite_a_long_name\n return function_with_quite_a_long_name_2(x - 1)\n File "err.py", line 10, in function_with_quite_a_long_name_2\n return function_with_quite_a_long_name(x)\n File "err.py", line 14, in function_with_quite_a_long_name\n return function_with_quite_a_long_name_2(x - 1)\n File "err.py", line 10, in function_with_quite_a_long_name_2\n return function_with_quite_a_long_name(x)\n File "err.py", line 14, in function_with_quite_a_long_name\n return function_with_quite_a_long_name_2
```

**Comment by Herudaio** [comment]
@wjaskowski thanks! 

The stdout/stderr is always logged "as-is" i.e. truncated. In case of an exception, the traceback field should capture the full stack trace. However, there seems to be a bug in the client and the stack trace is not split into separate lines and gets truncated as well.

I'll let you know when it's fixed in the client library :)

**Comment by wjaskowski** [comment]
Yes. Works now. If you want to make it nicer, then consider not removing the leading white characters:
monitoring/traceback:
```
2021/05/27 15:12:51 | File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py", line 40, in wrapped_fn
-- | --
2021/05/27 15:12:51 | return fn(*args, **kwargs)
2021/05/27 15:12:51 | File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune_pytorch_lightning/impl/__init__.py", line 338, in log_hyperparams
2021/05/27 15:12:51 | self.run[parameters_key] = params
2021/05/27 15:12:51 | File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune_pytorch_lightning/impl/__init__.py", line 288, in run
2021/05/27 15:12:51 | except NeptuneLegacyProjectException as e:
2021/05/27 15:12:51 | NameError: name 'NeptuneLegacyProjectException' is not defined
```
