### ISSUE TITLE
{"code":400,"errorType":"BAD_REQUEST","title":"Length of stream does not match given range"}

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-client#583]
Another random error. It seems that on upload.

```python
Unexpected error occurred in Neptune background thread: Killing Neptune asynchronous thread. All data is safe on disk and can be later synced manually using `neptune sync` command.
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/utils.py", line 61, in wrapper
    return func(*args, **kwargs)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_file_operations.py", line 183, in upload_raw_data
    response.raise_for_status()
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://app.neptune.ai//api/leaderboard/v1/attributes/upload?experimentId=5dbc90f0-596d-4c1b-a51d-fa65e92021c3&attribute=results%2F4%2Fy&ext=xr.nc

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/threading/daemon.py", line 54, in run
    self.work()
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py", line 181, in work
    self.process_batch(batch, version)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/threading/daemon.py", line 78, in wrapper
    result = func(self_, *args, **kwargs)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py", line 191, in process_batch
    result = self._processor._backend.execute_operations(self._processor._run_uuid, batch)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py", line 294, in execute_operations
    self._execute_upload_operations(run_uuid=run_uuid,
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py", line 310, in _execute_upload_operations
    error = upload_file_attribute(
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_file_operations.py", line 54, in upload_file_attribute
    _upload_loop(file_chunk_stream=FileChunkStream(upload_entry),
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_file_operations.py", line 147, in _upload_loop
    result = _upload_loop_chunk(chunk, file_chunk_stream, **kwargs)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_file_operations.py", line 165, in _upload_loop_chunk
    return upload_raw_data(data=chunk.get_data(), headers=headers, **kwargs)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/utils.py", line 96, in wrapper
    raise ClientHttpError(status_code, e.response.text) from e
neptune.new.exceptions.ClientHttpError: 

----ClientHttpError-----------------------------------------------------------------------

Neptune server returned status 400.

Server response was:
{"code":400,"errorType":"BAD_REQUEST","title":"Length of stream does not match given range"}

Verify the correctness of your call or contact Neptune support.
```

**Comment by wjaskowski** [comment]
Just to add, I got that with neptune-client 0.9.14 and without uploading sources so this might be different to #571. Very random and quite rare, I cannot provide a script to reproduce.

**Comment by aniezurawski** [comment]
Should not occur anymore in 0.9.15.

**Comment by ijmiller2** [comment]
FYI, I'm still getting this error with v0.9.16

**Comment by ijmiller2** [comment]
Also with v0.9.19 (just tried updating to latest version). For reference, I am using neptune via the R API (which I understand may still require some updates, but I can't seem to get a legacy version to work either).

**Comment by aniezurawski** [comment]
Hi @ijmiller2 

It really should not be possible to get the exact same error in 0.9.19 or something went wrong. Could you share a traceback?

**Comment by ijmiller2** [comment]
Hi @aniezurawski, thanks for the reply.

This is the full error I'm getting: 

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  NeptuneException: 

----ClientHttpError-----------------------------------------------------------------------

Neptune server returned status 400.

Server response was:
{"code":400,"errorType":"BAD_REQUEST","title":"Length of stream does not match given range"}

Verify the correctness of your call or contact Neptune support.

Need help?-> https://docs.neptune.ai/getting-started/getting-help


Detailed traceback:
  File "/fsx/home/imiller/.conda/envs/imiller/lib/python3.8/site-packages/neptune/__init__.py", line 226, in create_experiment
    return project.create_experiment(
  File "/fsx/home/imiller/.conda/envs/imiller/lib/python3.8/site-packages/neptune/projects.py", line 442, in create_experiment
    self._backend.upload_source_code(experiment, source_target_pairs)
  File "/fsx/home/imiller/.conda/envs/imiller/lib/python3.8/site-packages/neptune/internal/api_clients/hosted_api_clients/hosted_alpha_leaderboard_api_client.py", line 194, in
Calls: create_experiment -> <Anonymous> -> py_call_impl
Execution halted
```
