### ISSUE TITLE
MatchingResponseNotFound

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-client#591]
```
bravado                    11.0.3
bravado-core               5.17.0
neptune-client             0.9.16
```

Just happened:
```
Shutting down background jobs, please wait a moment...
Done!
Traceback (most recent call last):
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 335, in unmarshal_response
    incoming_response.swagger_result = unmarshal_response_inner(  # type: ignore
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 370, in unmarshal_response_inner
    response_spec = get_response_spec(status_code=response.status_code, op=op)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado_core/response.py", line 157, in get_response_spec
    raise MatchingResponseNotFound(
bravado_core.exception.MatchingResponseNotFound: Response specification matching http status_code 408 not found for operation Operation(getExperimentAttributes). Either add a response specification for the status_code or use a `default` response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/utils.py", line 61, in wrapper
    return func(*args, **kwargs)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py", line 384, in get_attributes
    run = self.leaderboard_client.api.getExperimentAttributes(**params).response().result
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 200, in response
    swagger_result = self._get_swagger_result(incoming_response)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 124, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 300, in _get_swagger_result
    unmarshal_response(
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 344, in unmarshal_response
    six.reraise(
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 335, in unmarshal_response
    incoming_response.swagger_result = unmarshal_response_inner(  # type: ignore
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 370, in unmarshal_response_inner
    response_spec = get_response_spec(status_code=response.status_code, op=op)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado_core/response.py", line 157, in get_response_spec
    raise MatchingResponseNotFound(
bravado.exception.HTTPRequestTimeout: 408 : Response specification matching http status_code 408 not found for operation Operation(getExperimentAttributes). Either add a response specification for the status_code or use a `default` response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 135, in evaluate
    agent = get_agent(cfg, run)
  File "main.py", line 92, in get_agent
    save_auxiliary_info(cfg, da, run)
  File "main.py", line 67, in save_auxiliary_info
    with neptune.init(pred_neptune_project, run=run_id, mode=RunMode.READ_ONLY) as pred_run:
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/init_impl.py", line 322, in init
    _run.sync(wait=False)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/run.py", line 453, in sync
    attributes = self._backend.get_attributes(self._uuid)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/utils.py", line 99, in wrapper
    raise NeptuneConnectionLostException() from last_exception
neptune.new.exceptions.NeptuneConnectionLostException: 

----NeptuneConnectionLostException---------------------------------------------------------

A connection to the Neptune server was lost.
If you are using asynchronous (default) connection mode Neptune automatically switched to an offline mode and your data is being stored safely on the disk.
You can upload it later using Neptune Command Line Interface:
    neptune sync -p workspace_name/project_name

What should I do?
    - Check if your computer is connected to the internet.
    - If your connection is unstable you can consider working using the offline mode:
        run = neptune.init(mode="offline")
        
You can read in detail how it works and how to upload your data on the following doc pages:
    - https://docs.neptune.ai/advanced-user-guides/connection-modes#offline
    - https://docs.neptune.ai/advanced-user-guides/uploading-offline-data
    
You may also want to check the following docs pages:
    - https://docs.neptune.ai/advanced-user-guides/connectivity-issues
    - https://docs.neptune.ai/advanced-user-guides/connection-modes
    
Need help?-> https://docs.neptune.ai/getting-started/getting-help

Warning: string series 'monitoring/stderr' value was longer than 1000 characters and was truncated. This warning is printed only once per series.
Shutting down background jobs, please wait a moment...
Done!
Waiting for the remaining 59 operations to synchronize with Neptune. Do not kill this process.
All 59 operations synced, thanks for waiting!
Traceback (most recent call last):
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 335, in unmarshal_response
    incoming_response.swagger_result = unmarshal_response_inner(  # type: ignore
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 370, in unmarshal_response_inner
    response_spec = get_response_spec(status_code=response.status_code, op=op)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado_core/response.py", line 157, in get_response_spec
    raise MatchingResponseNotFound(
bravado_core.exception.MatchingResponseNotFound: Response specification matching http status_code 408 not found for operation Operation(getExperimentAttributes). Either add a response specification for the status_code or use a `default` response.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/utils.py", line 61, in wrapper
    return func(*args, **kwargs)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py", line 384, in get_attributes
    run = self.leaderboard_client.api.getExperimentAttributes(**params).response().result
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 200, in response
    swagger_result = self._get_swagger_result(incoming_response)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 124, in wrapper
    return func(self, *args, **kwargs)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 300, in _get_swagger_result
    unmarshal_response(
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 344, in unmarshal_response
    six.reraise(
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 335, in unmarshal_response
    incoming_response.swagger_result = unmarshal_response_inner(  # type: ignore
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado/http_future.py", line 370, in unmarshal_response_inner
    response_spec = get_response_spec(status_code=response.status_code, op=op)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/bravado_core/response.py", line 157, in get_response_spec
    raise MatchingResponseNotFound(
bravado.exception.HTTPRequestTimeout: 408 : Response specification matching http status_code 408 not found for operation Operation(getExperimentAttributes). Either add a response specification for the status_code or use a `default` response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 191, in <module>
    main()
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/prime/config/cli.py", line 504, in invoke
    super().invoke(ctx)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/prime/config/decorators.py", line 423, in _fn
    return fn(*bound_args.args, **bound_args.kwargs)
  File "main.py", line 187, in main
    evaluate(cfg)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/prime/config/decorators.py", line 423, in _fn
    return fn(*bound_args.args, **bound_args.kwargs)
  File "main.py", line 135, in evaluate
    agent = get_agent(cfg, run)
  File "main.py", line 92, in get_agent
    save_auxiliary_info(cfg, da, run)
  File "main.py", line 67, in save_auxiliary_info
    with neptune.init(pred_neptune_project, run=run_id, mode=RunMode.READ_ONLY) as pred_run:
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/init_impl.py", line 322, in init
    _run.sync(wait=False)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/run.py", line 453, in sync
    attributes = self._backend.get_attributes(self._uuid)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/backends/utils.py", line 99, in wrapper
    raise NeptuneConnectionLostException() from last_exception
neptune.new.exceptions.NeptuneConnectionLostException: 

----NeptuneConnectionLostException---------------------------------------------------------

A connection to the Neptune server was lost.
If you are using asynchronous (default) connection mode Neptune automatically switched to an offline mode and your data is being stored safely on the disk.
You can upload it later using Neptune Command Line Interface:
    neptune sync -p workspace_name/project_name

What should I do?
    - Check if your computer is connected to the internet.
    - If your connection is unstable you can consider working using the offline mode:
        run = neptune.init(mode="offline")
        
You can read in detail how it works and how to upload your data on the following doc pages:
    - https://docs.neptune.ai/advanced-user-guides/connection-modes#offline
    - https://docs.neptune.ai/advanced-user-guides/uploading-offline-data
    
You may also want to check the following docs pages:
    - https://docs.neptune.ai/advanced-user-guides/connectivity-issues
    - https://docs.neptune.ai/advanced-user-guides/connection-modes
    
Need help?-> https://docs.neptune.ai/getting-started/getting-help
```

**Comment by wjaskowski** [comment]
Actually, Neptune is hanging in the same way as I described here: https://github.com/neptune-ai/neptune-pytorch-lightning/issues/6

**Comment by aniezurawski** [comment]
>This will be fixed in the next release of the client and the error is not expected to happen until then.
Actually it was a server-side issue. 408 status code was missing in our swagger so bravado library could not handle it properly.
It's fixed already.
