### ISSUE TITLE
OSError: [Errno 24] Too many open files: '.neptune/async/43a84836-afbe-4727-94e0-db2fdd835dba'

### ISSUE THREAD

**Issue by guangmingjian** [neptune-ai/neptune-client#677]
This project is so cool. But a problem occurred and I hope to get help.

I have configured the environment variables in ".bashrc ".

```
export NEPTUNE_API_TOKEN='YOUR_LONG_API_TOKEN'


```
then 
source .bashrc

And the code is as follows:

```
for i in range(140):
    nep_run = neptune.init(project=f'...',api_token = ...)
    nep_run["parameters"] = ...
    nep_run["metrics/m_test_acc"] = ...
    nep_run["metrics/s_test_acc"] = ...
    nep_run.stop()
```

But, when i is equal to 112, the following error will occur.

```
Error
Traceback (most recent call last):
  File "/data/mingjian/pythoncode/utils/neptuneutils/test_NepTools.py", line 24, in test_move_mflow_neptune
  File "/data/mingjian/pythoncode/utils/neptuneutils/NepTools.py", line 53, in move_mflow_neptune
  File "/data/mingjian/pythoncode/utils/neptuneutils/NepTools.py", line 42, in set_neptune
  File "/data/mingjian/anaconda3/envs/py37cu102/lib/python3.7/site-packages/neptune/new/internal/init_impl.py", line 283, in init
OSError: [Errno 24] Too many open files: '.neptune/async/43a84836-afbe-4727-94e0-db2fdd835dba'
```

I tried using the command 

```
ulimit -n 10000
```

But re-running is still the same problem.  Thanks!

**Comment by aniezurawski** [comment]
Hi @guangmingjian 

There was a leak of sockets in `stop()`. We fixed this issue in latest version (0.10.8). Please upgrade neptune-client. :)
