### ISSUE TITLE
BUG: Neptune hungs up on stop

### ISSUE THREAD

**Issue by wjaskowski** [neptune-ai/neptune-client#715]
In the recent days I have twice experienced neptune's client infinite hung up on `stop()` (I suppose) When I ctrl+c the process, I saw the following stacktrace:

```python
Waiting for the remaining 3 operations to synchronize with Neptune. Do not kill this process.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/run.py", line 271, in stop
    self._op_processor.stop(sec_left)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py", line 154, in stop
    self._wait_for_queue_empty(initial_queue_size=self._queue.size(), seconds=seconds)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py", line 118, in _wait_for_queue_empty
    self._queue.wait_for_empty(wait_time)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/neptune/new/internal/containers/disk_queue.py", line 142, in wait_for_empty
    self._event_empty.wait(seconds)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/wojciech/miniconda3/envs/nori/lib/python3.8/site-packages/ray/worker.py", line 803, in shutdown
    time.sleep(0.5)
KeyboardInterrupt

```

I am using the neptune run using the `with` statement.

It is true that I am still using an older version of the client (i.e., 0.9.16 because you made some backward-incompatible changes in the later versions and I had no time to upgrade) but this has been working robustly for a very long time so I am surprised that sth like that started to appear.

Of course, I cannot reproduce this. As I said this happened twice among hundreds of runs.

**Comment by aniezurawski** [comment]
Hi. This bug was already fixed in 0.10.8. Sorry for backward compatibility issues.
