### ISSUE TITLE
BUG: Max string attribute length exceeded error

### ISSUE THREAD

**Issue by chamathabeysinghe** [neptune-ai/neptune-client#765]
### Describe the bug
I am trying to train a faster R-CNN model with PyTorch lightning and Neptune logger. When I change the backbone from resnet34 to resnet101 get this error. 

### Traceback
```
Traceback (most recent call last):
  File "training_script_ant_dataset.py", line 160, in <module>
    trainer.fit(task,
  File "/dice1-data/home/cabe0006/Projects/py_environments/faster_rcnn/lib/python3.8/site-packages/pytorch_lightning-1.3.5-py3.8.egg/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/dice1-data/home/cabe0006/Projects/py_environments/faster_rcnn/lib/python3.8/site-packages/pytorch_lightning-1.3.5-py3.8.egg/pytorch_lightning/trainer/trainer.py", line 753, in _run
    self.pre_dispatch()
  File "/dice1-data/home/cabe0006/Projects/py_environments/faster_rcnn/lib/python3.8/site-packages/pytorch_lightning-1.3.5-py3.8.egg/pytorch_lightning/trainer/trainer.py", line 783, in pre_dispatch
    self.logger.log_hyperparams(self.lightning_module.hparams_initial)
  File "/dice1-data/home/cabe0006/Projects/py_environments/faster_rcnn/lib/python3.8/site-packages/pytorch_lightning-1.3.5-py3.8.egg/pytorch_lightning/utilities/distributed.py", line 49, in wrapped_fn
    return fn(*args, **kwargs)
  File "/dice1-data/home/cabe0006/Projects/py_environments/faster_rcnn/lib/python3.8/site-packages/pytorch_lightning-1.3.5-py3.8.egg/pytorch_lightning/loggers/neptune.py", line 247, in log_hyperparams
    self.experiment.set_property(f'param__{key}', val)
  File "/dice1-data/home/cabe0006/Projects/py_environments/faster_rcnn/lib/python3.8/site-packages/neptune_client-0.13.1-py3.8.egg/neptune/experiments.py", line 818, in set_property
    return self._backend.set_property(
  File "/dice1-data/home/cabe0006/Projects/py_environments/faster_rcnn/lib/python3.8/site-packages/neptune_client-0.13.1-py3.8.egg/neptune/utils.py", line 271, in wrapper
    return func(*args, **kwargs)
  File "/dice1-data/home/cabe0006/Projects/py_environments/faster_rcnn/lib/python3.8/site-packages/neptune_client-0.13.1-py3.8.egg/neptune/internal/api_clients/hosted_api_clients/hosted_alpha_leaderboard_api_client.py", line 231, in set_property
    self._execute_operations(
  File "/dice1-data/home/cabe0006/Projects/py_environments/faster_rcnn/lib/python3.8/site-packages/neptune_client-0.13.1-py3.8.egg/neptune/utils.py", line 271, in wrapper
    return func(*args, **kwargs)
  File "/dice1-data/home/cabe0006/Projects/py_environments/faster_rcnn/lib/python3.8/site-packages/neptune_client-0.13.1-py3.8.egg/neptune/internal/api_clients/hosted_api_clients/hosted_alpha_leaderboard_api_client.py", line 638, in _execute_operations
    raise ExperimentOperationErrors(errors=errors)
neptune.api_exceptions.ExperimentOperationErrors: Caused by:
        * Max string attribute length (16384) exceeded (22616).
```
### Environment
```
pytorch-lightning             1.3.5
neptune-client                0.13.1
neptune-contrib               0.28.1
Python 3.8.10
```

**Comment by Blaizzy** [comment]
Hey @chamathabeysinghe 

Prince Canuma here, a Data Scientist at Neptune.ai

You got this error because Neptune has a character length limit of **16384** for strings.

For example:
`run['text'] = long_string` 

In the code above, if the character length of `long_string` is bigger than **16384** it will cause this error ❌  and if it's less it will work fine ✅.


Possible workarounds:
* You can split the text into chunks, turn it into a list and log the list items as a string series. Docs: https://docs.neptune.ai/you-should-know/what-can-you-log-and-display#text 
* Or you can save the string into a text file and upload it to Neptune. Docs: https://docs.neptune.ai/api-reference/field-types#.upload

**Comment by Blaizzy** [comment]
Looking at your traceback, I think this line might be the one causing the error.

trainer.py -> line 783

`self.logger.log_hyperparams(self.lightning_module.hparams_initial)`

Please check the length of `lightning_module.hparams_initial`

**Comment by Blu3s1one** [comment]
Same error here, with exactly same model (Resnet101). Works fine with Resnet34 and Resnet50. Thanks for your anser Blaizzy I will look how I can manage it.


> Hey @chamathabeysinghe
> 
> Prince Canuma here, a Data Scientist at Neptune.ai
> 
> You got this error because Neptune has a character length limit of **16384** for strings.
> 
> For example: `run['text'] = long_string`
> 
> In the code above, if the character length of `long_string` is bigger than **16384** it will cause this error x and if it's less it will work fine white_check_mark.
> 
> Possible workarounds:
> 
>     * You can split the text into chunks, turn it into a list and log the list items as a string series. Docs: https://docs.neptune.ai/you-should-know/what-can-you-log-and-display#text
> 
>     * Or you can save the string into a text file and upload it to Neptune. Docs: https://docs.neptune.ai/api-reference/field-types#.upload

**Comment by Blaizzy** [comment]
Cool, most welcome @Blu3s1one!

It is my pleasure 😃 

Feel free to reach out again if you encounter any other issues!

I'm closing this issue for now 👍
