### ISSUE TITLE
I'm getting a 400 error: "End of range is outside of given length"

### ISSUE THREAD

**Issue by Blaizzy** [neptune-ai/neptune-client#767]
i am also getting similar error. The code is same as in #752 
```
Global seed set to 0
validation loss accuracy  0 0.53 0.68
validation loss accuracy  1 0.44 0.74
validation loss accuracy  2 0.41 0.78
validation loss accuracy  3 0.4 0.75
validation loss accuracy  4 0.4 0.78
validation loss accuracy  5 0.38 0.79
validation loss accuracy  6 0.39 0.78
validation loss accuracy  7 0.4 0.79
Unexpected error occurred in Neptune background thread: Killing Neptune asynchronous thread. All data is safe on disk and can be later synced manually using `neptune sync` command.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/talha/venv/lib/python3.8/site-packages/neptune/new/internal/backends/utils.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/home/talha/venv/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_file_operations.py", line 198, in upload_raw_data
    response.raise_for_status()
  File "/home/talha/venv/lib/python3.8/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://app.neptune.ai/api/leaderboard/v1/attributes/upload?experimentId=97e1dd32-9771-4562-92a4-7ad4728c8c6b&attribute=training%2Fmodel%2Fcheckpoints%2Flast.ckpt&ext=ckpt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/talha/venv/lib/python3.8/site-packages/neptune/new/internal/threading/daemon.py", line 54, in run
    self.work()
  File "/home/talha/venv/lib/python3.8/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py", line 177, in work
    self.process_batch(batch, version)
  File "/home/talha/venv/lib/python3.8/site-packages/neptune/new/internal/threading/daemon.py", line 78, in wrapper
    result = func(self_, *args, **kwargs)
  File "/home/talha/venv/lib/python3.8/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py", line 187, in process_batch
    result = self._processor._backend.execute_operations(self._processor._run_id, batch)
  File "/home/talha/venv/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py", line 349, in execute_operations
    self._execute_upload_operations_with_400_retry(
  File "/home/talha/venv/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py", line 414, in _execute_upload_operations_with_400_retry
    raise ex
  File "/home/talha/venv/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py", line 411, in _execute_upload_operations_with_400_retry
    return self._execute_upload_operations(run_id, upload_operations)
  File "/home/talha/venv/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py", line 374, in _execute_upload_operations
    error = upload_file_attribute(
  File "/home/talha/venv/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_file_operations.py", line 56, in upload_file_attribute
    _upload_loop(file_chunk_stream=FileChunkStream(upload_entry),
  File "/home/talha/venv/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_file_operations.py", line 162, in _upload_loop
    result = _upload_loop_chunk(chunk, file_chunk_stream, query_params=query_params.copy(), **kwargs)
  File "/home/talha/venv/lib/python3.8/site-packages/neptune/new/internal/backends/hosted_file_operations.py", line 180, in _upload_loop_chunk
    return upload_raw_data(data=chunk.get_data(), headers=headers, query_params=query_params, **kwargs)
  File "/home/talha/venv/lib/python3.8/site-packages/neptune/new/internal/backends/utils.py", line 106, in wrapper
    raise ClientHttpError(status_code, e.response.text) from e
neptune.new.exceptions.ClientHttpError: 

----ClientHttpError-----------------------------------------------------------------------

Neptune server returned status 400.

Server response was:
{"errorType":"BAD_REQUEST","code":400,"title":"End of range is outside of given length"}

Verify the correctness of your call or contact Neptune support.

Need help?-> https://docs.neptune.ai/getting-started/getting-help

validation loss accuracy  8 0.39 0.79
validation loss accuracy  9 0.39 0.8
```

_Originally posted by @talhaanwarch in https://github.com/neptune-ai/neptune-client/issues/751#issuecomment-980778809_

**Comment by Blaizzy** [comment]
@talhaanwarch

I'm going to talk to the devs and get back to you on this issue

**Comment by Blaizzy** [comment]
But before I do

**Comment by Blaizzy** [comment]
According to the devs:

"The file was changed during upload, precisely the `last.cpkt` file is being updated intensively"

One workaround is to initialise the run in `sync` mode.

**Pytorch lightning example:** 

`run = neptune.init(..., mode='sync')`
`
neptune_logger = NeptuneLogger( run=run, log_model_checkpoints=True)`

**Docs**: https://docs.neptune.ai/you-should-know/connection-modes#synchronous

**Comment by Blaizzy** [comment]
Please try it and let me know if it works so I can add this to the Jira ticket 👍

**Comment by talhaanwarch** [comment]
hi @Blaizzy what if i turned off log_model_checkpoints? btw i will test it. checkpoints are large in size and may cause issue while uploading

**Comment by Blaizzy** [comment]
Hi @talhaanwarch 

That might work, and you can still log the best checkpoint after training is done 👍 .

**Comment by Blaizzy** [comment]
Let me know if it did actually work for you

**Comment by Blaizzy** [comment]
Hey @talhaanwarch  any progress

**Comment by talhaanwarch** [comment]
@Blaizzy i have turned the model checkpoint log off and apparently i cant see the error

**Comment by Blaizzy** [comment]
Hey @talhaanwarch

That's good,

I had another insight. Since NeptuneLogger logs checkpoints through [ModelCheckpoint Callback](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.model_checkpoint.html#pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint) and this issue is probably happening because the ModelCheckpoint is updating the same file that Neptune is trying to upload. Perhaps avoiding the use of the `save_last` argument in [ModelCheckpoint Callback](https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.model_checkpoint.html#pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint), which pretty much creates and updates the same file all the time, can solve the problem and allow you to continue to log checkpoints to Neptune normally.

Please try this and let me know if it solves your issue 👍

**Comment by Blaizzy** [comment]
Hey @talhaanwarch 

Happy new year 🥳 

Any updates?

**Comment by Blaizzy** [comment]
Hey @talhaanwarch,

I'm closing this issue,

Feel free to comment so I can re-open if your problem is not solved.

**Comment by Bavesh-B** [comment]
Hey @Blaizzy, I am having the same issue as @talhaanwarch and it is indeed the last.ckpt that is creating the problem. But I would like to save the last.ckpt after every epoch, just to resume training. In order to do this, will I have to save it manually without using the ModelCheckpoint callback. It would be really helpful if I could get some clarity on this query.

**Comment by Blaizzy** [comment]
Hi @Bavesh-B,

If you are saving it manually you can save multiple files and upload them individually.
Example: 

```
run = neptune.init(...)
for epoch in epochs:
       model.save(f"./path/model_{epoch}.ckpt")
       run[f"models/model_{epoch}"].upload("./path/model_{epoch}.ckpt")
```

Or all in one go.

```

run = neptune.init(...)
for epoch in epochs:
       model.save(f"./path/model_{epoch}.ckpt")

run["models"].upload_files("./path/*.ckpt")
```


Let me know if this helps
